version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=12345678
      - MINIO_SECRET_KEY=password
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - ./storage/minio:/data